
  name: app_admin
  description: "Aplicativo administrativo da Vó Naná"

  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: ">=3.0.0 <4.0.0"

  dependencies:
    flutter:
      sdk: flutter

    dio: ^5.9.2

    cupertino_icons: ^1.0.8
    postgres: ^3.1.2
    http: ^1.1.0
    shared_preferences: ^2.2.2


    sqflite: ^2.3.0
    path: ^1.8.3
    crypto: ^3.0.3

    # Relatórios PDF
    pdf: ^3.11.0
    printing: ^5.13.4
    intl: ^0.20.2
    share_plus: ^13.1.0
    csv: ^8.0.0
    path_provider: ^2.1.5
    sqflite_common_ffi_web: ^1.1.1

  dev_dependencies:
    flutter_test:
      sdk: flutter

    flutter_lints: ^6.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/images/

